### ISSUE TITLE
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'train'

### ISSUE THREAD

**Issue by yuanyuansiyuan** [hsqmlzno1/HATN#4]
when i use the commdand 'python extract_pivots.py --train --test -s dvd [source_domain] -t electronics [target_domain] -v [verbose]', this kind of command line lag unknown error occurs. Can you give some guide to fix it? Thank you!

**Comment by hsqmlzno1** [comment]
python extract_pivots.py --train --test -s dvd  -t electronics  -v 
[] is just descriptions.

**Comment by hsqmlzno1** [comment]
python extract_pivots.py --train --test -s dvd -t electronics -v
[] are just descriptions.

**Comment by yuanyuansiyuan** [comment]
But i still get the same error.

**Comment by haoyanbin918** [comment]
I also met this error. When running: python train_hatn.py --train --test -s book -t dvd -v, an error "absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'train' " occurs. Could you please help to fix it? Many thanks.

**Comment by hsqmlzno1** [comment]
Could you give me more information? Which line the error occurs in？

**Comment by yuanyuansiyuan** [comment]
Here is the error info 

Traceback (most recent call last):
  File "extract_pivots.py", line 12, in <module>
    np.random.seed(FLAGS.random_seed)
  File "/home/cbd109/.local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/cbd109/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 632, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'train'

**Comment by haoyanbin918** [comment]
> Could you give me more information? Which line the error occurs in？
Here it is.
File "train_hatn.py", line 15, in <module>
 File "/home/robin/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/robin/anaconda2/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 632, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'train'

**Comment by hsqmlzno1** [comment]
What's the version of Tensorflow?

**Comment by yuanyuansiyuan** [comment]
tensorflow 1.10.1 tensorflow-gpu 1.4

**Comment by yuanyuansiyuan** [comment]
i upgrade tensorflow to 1.4, its ok now. Thank you!

**Comment by haoyanbin918** [comment]
tensorflow 1.11.0

**Comment by hsqmlzno1** [comment]
OK. I think the version is old.

**Comment by haoyanbin918** [comment]
Ok, I will upgrade it. Thanks.

**Comment by haoyanbin918** [comment]
While the version 1.11.0 is very new, much newer than 1.4.0. Because it is too new?

**Comment by hsqmlzno1** [comment]
Maybe appropriate version is fine.

**Comment by haoyanbin918** [comment]
Hi, I meet another error when runing "python train_hatn.py --train --test -s books -t dvd -v". Could you please help check it, thanks.
Traceback (most recent call last):
  File "train_hatn.py", line 141, in <module>
    val_acc, _  = model.eval_sen(sess, x_val, word_mask_val, sent_mask_val, y_val, batch_size=FLAGS.batch_size)
  File "/home/yanbin/CDSC_TKDE/HATN/models/hatn.py", line 153, in eval_sen
    xb, wmb, smb = batch_generator.next_batch()
  File "/home/yanbin/CDSC_TKDE/HATN/models/nn_utils.py", line 129, in next_batch
    if self.word_mask != None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by yuanyuansiyuan** [comment]
change the "if self.word_mask != None"  to "if self.word_mask is not None:". I just search web to find this answer.

**Comment by haoyanbin918** [comment]
It is work now. Many thanks.
